export const animojes = [
    {
        id:1,
        status:false,
        title:'Радість',
        description:'Oдна з основних позитивних емоцій людини, внутрішнє почуття задоволення і щастя.',
        img: '../img/animoji/sticker.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B4%D1%96%D1%81%D1%82%D1%8C',
    },
    {
        id:2,
        status:false,
        title:'Любов',
        description:'Почуття глибокої сердечної прихильності, що охоплює низку сильних і позитивних емоційних і психічних станів.',
        img: '../img/animoji/sticker1.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%A1%D0%BE%D0%BD%D0%BB%D0%B8%D0%B2%D1%96%D1%81%D1%82%D1%8C#:~:text=%D0%A1%D0%BE%D0%BD%D0%BB%D0%B8%D0%B2%D1%96%D1%81%D1%82%D1%8C%20%E2%80%94%20%D1%81%D1%83%D0%B1\'%D1%94%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%B5%20%D0%B2%D1%96%D0%B4%D1%87%D1%83%D1%82%D1%82%D1%8F%20%D1%81%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D1%97,%D1%96%D0%BD%D1%88%D0%BE%D0%B3%D0%BE%20%D0%B7%D1%83%D1%81%D0%B8%D0%BB%D0%BB%D1%8F%20%D0%B4%D0%BB%D1%8F%20%D0%B9%D0%BE%D0%B3%D0%BE%20%D0%BF%D1%80%D0%B8%D0%BF%D0%B8%D0%BD%D0%B5%D0%BD%D0%BD%D1%8F.',
    },
    {
        id:3,
        status:false,
        title:'Здивування',
        description:'Когнітивна емоція, що виникає при виникненні несподіваної ситуації.',
        img: '../img/animoji/sticker2.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%97%D0%B4%D0%B8%D0%B2%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F',
    },
    {
        id:4,
        status:false,
        title:'Сонливість',
        description:'Суб\'єктивне відчуття сильної втоми й розслаблення, яке потребує вольового чи іншого зусилля для його припинення.',
        img: '../img/animoji/sticker3.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%A1%D0%BE%D0%BD%D0%BB%D0%B8%D0%B2%D1%96%D1%81%D1%82%D1%8C',
    },
    {
        id:5,
        status:false,
        title:'Везучість',
        description:'Момент, коли зловив бика за рога.',
        img: '../img/animoji/sticker5.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%A3%D0%B4%D0%B0%D1%87%D0%B0',
    },
    {
        id:6,
        status:false,
        title:'Сум',
        description:'Виникає у разі значної незадоволеності людини у будь-яких аспектах її життя.',
        img: '../img/animoji/sticker6.png',
        wiki: 'https://ru.wikiquote.org/wiki/%D0%9F%D0%B5%D1%87%D0%B0%D0%BB%D1%8C',
    },
    {
        id:7,
        status:false,
        title:'Ідейність',
        description:'система концептуально оформлених ідей, що виражає інтереси, світогляд.',
        img: '../img/animoji/sticker7.png',
        wiki: 'https://ru.wiktionary.org/wiki/%D0%B8%D0%B4%D0%B5%D0%B9%D0%BD%D0%BE%D1%81%D1%82%D1%8C',
    },
    {
        id:8,
        status:false,
        title:'Загадковість',
        description:'Oдна з основних позитивних емоцій людини, внутрішнє почуття задоволення і щастя.',
        img: '../img/animoji/sticker8.png',
        wiki: 'https://ru.wiktionary.org/wiki/%D0%B7%D0%B0%D0%B3%D0%B0%D0%B4%D0%BE%D1%87%D0%BD%D0%BE%D1%81%D1%82%D1%8C',
    },
    {
        id:9,
        status:false,
        title:'Хворобливість',
        description:'Здатність когось заразити через хворобу.',
        img: '../img/animoji/sticker9.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%A5%D0%B2%D0%BE%D1%80%D0%BE%D0%B1%D0%BB%D0%B8%D0%B2%D1%96%D1%81%D1%82%D1%8C',
    },
    {
        id:10,
        status:false,
        title:'Лють',
        description:'Перезбуджений стан царини мозку, котрий впливає на формування психікою негативних емоційних відчуттів у свідомості людини.',
        img: '../img/animoji/sticker10.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%9B%D1%8E%D1%82%D1%8C',
    },
    {
        id:11,
        status:false,
        title:'Закоханість',
        description:'сильне людське почуття (комплекс почуттів), об\'єктом якого є інша особистість.',
        img: '../img/animoji/sticker11.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%97%D0%B0%D0%BA%D0%BE%D1%85%D0%B0%D0%BD%D1%96%D1%81%D1%82%D1%8C',
    },
    {
        id:12,
        status:false,
        title:'Святковість',
        description:'Час пригод.',
        img: '../img/animoji/sticker12.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%A1%D0%B2%D1%8F%D1%82%D0%BE',
    },
    {
        id:13,
        status:false,
        title:'Любиобільність',
        description:'Здатність любити сильно чи багатьох.',
        img: '../img/animoji/sticker13.png',
        wiki: 'https://ru.wiktionary.org/wiki/%D0%BB%D1%8E%D0%B1%D0%B2%D0%B5%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C',
    },
    {
        id:14,
        status:false,
        title:'Нецензурність',
        description:'Намагання щось яскраво й негативно зобразити.',
        img: '../img/animoji/sticker14.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%9D%D0%B5%D0%BD%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D0%B0_%D0%BB%D0%B5%D0%BA%D1%81%D0%B8%D0%BA%D0%B0',
    },
    {
        id:15,
        status:false,
        title:'Сумнів',
        description:'Загадкова й безаргументовна поведінка або прийняття нераціональних рішень.',
        img: '../img/animoji/sticker15.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%A1%D1%83%D0%BC%D0%BD%D1%96%D0%B2',
    },
    {
        id:16,
        status:false,
        title:'Таємничість',
        description:'Загадкова й безаргументовна поведінка або прийняття нераціональних рішень.',
        img: '../img/animoji/sticker16.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%A2%D0%B0%D1%94%D0%BC%D0%BD%D0%B8%D1%86%D1%8F',
    },
    {
        id:17,
        status:false,
        title:'Медитативність',
        description:'Знаходження спокою буквально в будь-який момент чи ситуацію.',
        img: '../img/animoji/sticker17.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B4%D0%B8%D1%82%D0%B0%D1%86%D1%96%D1%8F_(%D0%B6%D0%B0%D0%BD%D1%80)',
    },
    {
        id:18,
        status:false,
        title:'Страх',
        description:'Стан хвилювання, тривоги, неспокою, викликаний очікуванням чого-небудь неприємного та небажаного.',
        img: '../img/animoji/sticker18.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%85)',
    },
    {
        id:19,
        status:false,
        title:'Згода',
        description:'Погодитися із чиїмось рішенням.',
        img: '../img/animoji/sticker19.png',
        wiki: 'https://ru.wikipedia.org/wiki/%D0%97%D0%B3%D0%BE%D0%B4%D0%B0',
    },
    {
        id:20,
        status:false,
        title:'Незгода',
        description:'Не погодитися із чиїмось рішенням.',
        img: '../img/animoji/sticker20.png',
        wiki: 'https://ru.wikipedia.org/wiki/%D0%97%D0%B3%D0%BE%D0%B4%D0%B0',
    },
    {
        id:21,
        status:false,
        title:'Щастя',
        description:'Психоемоційний стан цілковитого вдоволення життям, відчуття глибокого задоволення та радості.',
        img: '../img/animoji/sticker21.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%A9%D0%B0%D1%81%D1%82%D1%8F',
    },
    {
        id:22,
        status:false,
        title:'Обіймолюбивий',
        description:'Психологічний стан, коли людині хочеться якумога-більше обіймів.',
        img: '../img/animoji/sticker22.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%9E%D0%B1%D1%96%D0%B9%D0%BC%D0%B8',
    },
    {
        id:23,
        status:false,
        title:'Братерність',
        description:'Велика схильність до дружнього відношення до оточуючих.',
        img: '../img/animoji/sticker23.png',
        wiki: 'http://wiki.kubg.edu.ua/%D0%91%D1%80%D0%B0%D1%82%D0%B5%D1%80%D0%BD%D1%96%D0%B9',
    },
    {
        id:24,
        status:false,
        title:'Незручність',
        description:'Емоційний стан, коли зробив щось не так і знаходишся у схвильованому стані.',
        img: '../img/animoji/sticker24.png',
        wiki: 'https://ru.wiktionary.org/wiki/%D0%BD%D0%B5%D0%B7%D1%80%D1%83%D1%87%D0%BD%D1%96%D1%81%D1%82%D1%8C',
    },
    {
        id:25,
        status:false,
        title:'Комунікабельність',
        description:'Здатність людини до спілкування, до встановлення соціальних зв\'язків, контактів, до плідної взаємодії з іншими людьми.',
        img: '../img/animoji/sticker25.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BC%D1%83%D0%BD%D1%96%D0%BA%D0%B0%D0%B1%D0%B5%D0%BB%D1%8C%D0%BD%D1%96%D1%81%D1%82%D1%8C',
    },
    {
        id:26,
        status:false,
        title:'Світозакоханність',
        description:'Любов до усього оточуючого світу.',
        img: '../img/animoji/sticker26.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%9C%D0%B8%D1%80%D0%BE%D0%BB%D1%8E%D0%B1%D0%BD%D0%B5',
    },
    {
        id:27,
        status:false,
        title:'Критичність',
        description:'Ретельно обмірковання о незалежних рішеннях.',
        img: '../img/animoji/sticker27.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%9A%D1%80%D0%B8%D1%82%D0%B8%D1%87%D0%BD%D0%B5_%D0%BC%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F',
    },
    {
        id:28,
        status:false,
        title:'Щасливість',
        description:'Oдна з основних позитивних емоцій людини, внутрішнє почуття задоволення і щастя.',
        img: '../img/animoji/sticker28.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%A9%D0%B0%D1%81%D1%82%D1%8F',
    },
    {
        id:29,
        status:false,
        title:'Обережність',
        description:'Бути ретельним й дуже уважним',
        img: '../img/animoji/sticker29.png',
        wiki: 'http://wiki.kubg.edu.ua/%D0%9E%D0%B1%D0%B5%D1%80%D0%B5%D0%B6%D0%BD%D1%96%D1%81%D1%82%D1%8C',
    },
    {
        id:30,
        title:'Задумливість',
        description:'Oдна з основних емоцій людини, внутрішнє почуття сумніву.',
        img: '../img/animoji/sticker30.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%A1%D1%83%D0%BC%D0%BD%D1%96%D0%B2',
    },
    {
        id:31,
        status:false,
        title:'Здивованість',
        description: 'Когнітивна емоція, що виникає при виникненні несподіваної ситуації.',
        img: '../img/animoji/sticker31.png',
        wiki: 'https://uk.wikipedia.org/wiki/%D0%97%D0%B4%D0%B8%D0%B2%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F',
    },
    {
        id:32,
        status:false,
        title:'Капризний',
        description:'Людина, що багато чого хоче.',
        img: '../img/animoji/sticker32.png',
        wiki: 'https://ru.wiktionary.org/wiki/%D0%BA%D0%B0%D0%BF%D1%80%D0%B8%D0%B7%D0%BD%D1%8B%D0%B9',
    },
    {
        id:33,
        status:false,
        title:'Зосереджений',
        description:'Емоція коли людина дуже пильно щось робить.',
        img: '../img/animoji/sticker33.png',
        wiki: 'https://ru.wiktionary.org/wiki/%D1%81%D0%BE%D1%81%D1%80%D0%B5%D0%B4%D0%BE%D1%82%D0%BE%D1%87%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9',
    },
    {
        id:34,
        status:false,
        title:'Привітливий',
        description:'Ознака дружелюної людини.',
        img: '../img/animoji/sticker34.png',
        wiki: 'https://ru.wiktionary.org/wiki/%D0%BF%D1%80%D0%B8%D0%B2%D1%96%D1%82%D0%BB%D0%B8%D0%B2%D0%B8%D0%B9',
    },
    {
        id:35,
        status:false,
        title:'Незнання',
        description:'Відчуття, коли нічого не з\'являться в голові ніякої ідеї.',
        img: '../img/animoji/sticker35.png',
        wiki: '',
    },
    {
        id:36,
        status:false,
        title:'Дратівливість',
        description:'Відчуття, коли тебе все бісить.',
        img: '../img/animoji/sticker37.png',
        wiki: '',
    },
    {
        id:37,
        status:false,
        title:'Подив',
        description:'Великий рівень здивованності.',
        img: '../img/animoji/sticker38.png',
        wiki: '',
    },
    {
        id:38,
        status:false,
        title:'Злість',
        description:'Негативна емоція, яка з\'являється через високий рівень подразників.',
        img: '../img/animoji/sticker39.png',
        wiki: '',
    },
    {
        id:39,
        status:false,
        title:'Підлабузництво',
        description:'Похвала з корисливою метою, підлабузництво, лукава догідливість, удаване схвалення, принижене потурання.',
        img: '../img/animoji/sticker40.png',
        wiki: 'https://ru.wiktionary.org/wiki/%D0%BF%D1%96%D0%B4%D0%BB%D0%B0%D0%B1%D1%83%D0%B7%D0%BD%D0%B8%D1%86%D1%82%D0%B2%D0%BE',
    }, 
]

export const socials = [
    {
        title:'Instagram',
        url: '../img/icons/Instagram-Logo.wine.svg',
        https:'https://www.instagram.com/a_belous1/',
    },
    {
        title:'Twitter',
        url: '../img/icons/Twitter-Logo.wine.svg',
        https:'https://twitter.com/airdray1',
    },
    {
        title:'Gmail',
        url: '../img/icons/Gmail-Logo.wine.svg',
        https:'mailto:belous50409@gmail.com',
    },
    {
        title:'GitHub',
        url: '../img/icons/GitHub-Logo.wine.svg',
        https:'https://github.com/AirDray1',
    },
    {
        title:'LinkedIn',
        url: '../img/icons/LinkedIn-Icon-Logo.wine.svg',
        https:'https://www.linkedin.com/in/%D0%B0%D0%BD%D0%B4%D1%80%D0%B5%D0%B9-%D0%B1%D0%B5%D0%BB%D0%BE%D1%83%D1%81-343a19232/',
    },
]